config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords'}
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get '/about' => 'home#about', as: :about

  resources :users, only: [:new, :create, :show]
  resources :posts do
    resources :comments
    resources :favourites, only: [:create, :destroy]
  end

  root 'home#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_many :comments, dependent: :nullify
  has_many :favourites, dependent: :destroy
  has_many :favouriting_users, through: :favourites, source: :user

  validates :title, presence: true, uniqueness: true
  validates :body, presence: true

  def favourited_by?(user)
    favourite_for(user).present?
  end

  def favourite_for(user)
    favourites.find_by_user_id user.id
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    if user_signed_in?
      @post = Post.new
    else
      redirect_to new_user_session_path, alert:"Log in Please!"
    end
  end

  def create
    post_params = params.require(:post).permit([:title, :body])
    @post = Post.new post_params
    @post.user = current_user
    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def show
    if user_signed_in?
      @post = Post.find params[:id]
      @comment = Comment.new
    else
      redirect_to new_user_session_path, alert:"Log in Please!"
    end
  end

  def index
    @posts = Post.all
  end

  def edit
    @post = Post.find params[:id]
    if current_user != @post.user
      redirect_to root_path, alert: "You did not build this Post"
    end
  end

  def update
    post_params = params.require(:post).permit([:title, :body])
    @post = Post.find params[:id]
    if @post.update(post_params)
      redirect_to post_path(@post), notice: "Post Updated!"
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find params[:id]
    @post.destroy
    flash[:notice] = "Post deleted Successfully."
    redirect_to posts_path
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= form_for @post do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control"%>
  </div>
  <br>
    <%= f.submit class: "btn btn-primary"%>
  <% end %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="well">
    <%= link_to post.title + " : " + post.body.first(50) + " ...", post_path(post) %>
    <br>
  </div>
<% end %>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <br>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body , class: "form-control" %>
  </div>
  <br>
  <%= f.submit class: "btn btn-primary edit-right"%>
<% end %>
<%= @post.errors.full_messages.join(", ") %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<br>
<div class="well">
  <%= @post.body %>
  <% if user_signed_in? && @post.user == current_user %>
    <%= link_to "Delete", post_path(@post), method: :delete,
            class: "btn btn-danger btn-sm delete-right", data: {confirm: "Are you use you want to delete this post?"} %>
    <%= link_to "Edit", edit_post_path(@post),
            class: "btn btn-info btn-sm edit-right"%>
  <% end %>

</div>
  <% if user_signed_in? && @post.favourited_by?(current_user) %>
    <%= link_to fa_icon("star 2x"), [@post, @post.favourite_for(current_user)],
                method: :delete, class: "icon-big" %>
  <% else %>
    <%= link_to fa_icon("star-o 2x"), post_favourites_path(@post), method: :post,
                class: "icon-big" %>
  <% end %>
  Favourited: <%= pluralize(@post.favourites.count, "time") %>

<br>
<br>
<br>

<%= form_for [@post,@comment] do |f| %>
  <div class="form-group">
    <%= f.label :body, "Create New Comments" %>
    <br>
    <%= f.text_area :body, class: "form-control"%>
  </div>
  <%= f.submit class: "btn btn-primary edit-right" %>
  <br>
<% end %>

<%= @comment.errors.full_messages.join(", ") %>

<% @post.comments.order('created_at DESC').each do |comment| %>
  <% if comment %>
  <h2> Comments </h2>
    <div class="well">
      <%= comment.body %>
      <% if user_signed_in? && comment.user == current_user %>
        <%= link_to "Delete", post_comment_path(@post, comment),
            method: :delete,
            class: "btn btn-danger btn-sm delete-right",
            data: {confirm: "Are you sure?"} %>
      <% end %>
    </div>
  <% end %>
<% end %>