config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords'}
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get '/about' => 'home#about', as: :about

  resources :users, only: [:new, :create, :show]
  resources :posts do
    resources :comments
    resources :favourites, only: [:create, :destroy]
  end

  root 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

  # user here is essentially current_user and it may be nil
  # we set it to User.new if it's nil:
  user ||= User.new

  # We define an ability in here that states that only the user who created
  # a question is able to 'manage' the question. :manage here includes any
  # operation such as: destroy, edit, delete, approve...ect
  can :manage, Post do |p|
    user == p.user
  end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts, dependent: :nullify
  
  validates :title, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :body, presence: true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_many :comments, dependent: :nullify
  has_many :favourites, dependent: :destroy
  has_many :favouriting_users, through: :favourites, source: :user

  validates :title, presence: true, uniqueness: true
  validates :body, presence: true

  def favourited_by?(user)
    favourite_for(user).present?
  end

  def favourite_for(user)
    favourites.find_by_user_id user.id
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts, dependent: :nullify
  has_many :comments, dependent: :nullify
  has_many :posts_comments, through: :posts, source: :comments
  has_many :favourites, dependent: :nullify
  has_many :favourite_posts, through: :favourites, source: :post


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    stored_location_for(resource) ||
      if resource.is_a?(Admin)
        admin_dashboard_path
      else
        root_path
      end
  end

  def after_sign_out_path_for(resource_or_scope)
    request.referrer
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name
    devise_parameter_sanitizer.for(:sign_up) << :last_name
    devise_parameter_sanitizer.for(:account_update) << :first_name
    devise_parameter_sanitizer.for(:account_update) << :last_name
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment_params = params.require(:comment).permit(:body)
    @post = Post.find params[:post_id]
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    @comment.post = @post
    if @comment.save
      redirect_to post_path(@post), notice: "Your comment created successfully!"
    else
      render "posts/show", alert: "An error has occured"
    end
  end
  #
  # def edit
  #
  # end
  #
  # def update
  #
  # end
  #
  def destroy
    comment = Comment.find params[:id]
    comment.destroy
    redirect_to post_path(comment.post), notice: "Comment deleted"
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  def create
    fav      = current_user.favourites.new
    post     = Post.find params[:post_id]
    fav.post = post
    if fav.save
      redirect_to post_path(post), notice: "Favourited!"
    else
      redirect_to post_path(post), alert: "Error occured!"
    end
  end

  def destroy
    post     = Post.find params[:post_id]
    fav      = current_user.favourites.find params[:id]
    fav.destroy
    redirect_to post_path(post), notice: "Un-Favourited!"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    if user_signed_in?
      @post = Post.new
    else
      redirect_to new_user_session_path, alert:"Log in Please!"
    end
  end

  def create
    post_params = params.require(:post).permit([:title, :body])
    @post = Post.new post_params
    @post.user = current_user
    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def show
    if user_signed_in?
      @post = Post.find params[:id]
      @comment = Comment.new
    else
      redirect_to new_user_session_path, alert:"Log in Please!"
    end
  end

  def index
    @posts = Post.all
  end

  def edit
    @post = Post.find params[:id]
    if current_user != @post.user
      redirect_to root_path, alert: "You did not build this Post"
    end
  end

  def update
    post_params = params.require(:post).permit([:title, :body])
    @post = Post.find params[:id]
    if @post.update(post_params)
      redirect_to post_path(@post), notice: "Post Updated!"
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find params[:id]
    @post.destroy
    flash[:notice] = "Post deleted Successfully."
    redirect_to posts_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # def new
  #   @user = User.new
  # end
  #
  # def create
  #   user_params = params.require(:user).permit(:first_name, :last_name, :email,
  #                                              :password, :password_confirmation)
  #   @user = User.new user_params
  #   if @user.save
  #     session[:user_id] = @user_id
  #     redirect_to root_path, notice: "Acount Created!"
  #   else
  #     render :new
  #   end
  # end

  def show
    unless user_signed_in?
      redirect_to root_path
    end
  end

  def show
    if user_signed_in?
        @user = User.find params[:id]
      if user_signed_in? && @user == current_user
        @user = User.find params[:id]
        @favourites = @user.favourites
      else
        redirect_to root_path, alert: "You are not allowed!"
      end
    else
      redirect_to new_user_session_path, alert:"Log in Please!"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= root_path %>"><i class="glyphicon glyphicon-home"></i> Home</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "<i class='glyphicon glyphicon-user'></i> About".html_safe, about_path %></li>
        <li><%= link_to "<i class='glyphicon glyphicon-plus'></i>New Post".html_safe, new_post_path %></li>
        <li><%= link_to "<i class='glyphicon glyphicon-plus'></i>Posts".html_safe, posts_path %></li>

      </ul>
      <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> Account Setting <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <% if !user_signed_in? %>
                <li><%= link_to "LOG IN", new_user_session_path%></li>
                <li><%= link_to "CREATE FREE ACCOUNT", new_user_registration_path %></li>
              <% else %>
                <li><%= link_to "My Favourites", user_path(current_user.id) %>
                <li><%= link_to "Edit", edit_user_registration_path %></li>
                <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
              <% end %>
            </ul>
          </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
</head>
<body>
  <div class="container">
    <%= render "/layouts/nav" %>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>

  </div>
</body>
</html>